# Generated by Django 5.2.1 on 2025-06-06 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_api', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compliancereport',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='generated_by',
            field=models.ForeignKey(blank=True, help_text='User who generated this report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reports_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='reviewed_by_fleet_manager',
            field=models.BooleanField(default=False, help_text='Whether this report has been reviewed by fleet management'),
        ),
        migrations.AddField(
            model_name='hosperiod',
            name='verified_by_driver',
            field=models.BooleanField(default=False, help_text='Whether this period has been verified by the driver'),
        ),
        migrations.AddField(
            model_name='route',
            name='calculated_by',
            field=models.ForeignKey(blank=True, help_text='User who calculated this route', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_calculated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stops',
            name='is_optimized_stop',
            field=models.BooleanField(default=False, help_text='Whether this stop was created through route optimization'),
        ),
        migrations.AddField(
            model_name='stops',
            name='optimization_notes',
            field=models.TextField(blank=True, help_text='Notes about optimizations applied to this stop'),
        ),
        migrations.AddField(
            model_name='trip',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, help_text='Vehicle assigned for this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='users.vehicle'),
        ),
        migrations.AddField(
            model_name='trip',
            name='company',
            field=models.ForeignKey(default=1, help_text='Company this trip belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='users.spottercompany'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this trip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(default=1, help_text='Driver who owns this trip', limit_choices_to={'is_active_driver': True, 'is_driver': True}, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the trip', max_length=20),
        ),
        migrations.AlterField(
            model_name='hosperiod',
            name='related_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hos_periods', to='trip_api.stops'),
        ),
        migrations.AlterField(
            model_name='stops',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stops',
            name='stop_type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('fuel', 'Fuel Stop'), ('rest', 'Rest Break'), ('mandatory_break', 'Mandatory 30-min Break'), ('daily_reset', 'Daily 10-hour Reset'), ('fuel_and_break', 'Combined Fuel & Break')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['trip', '-created_at'], name='trip_api_co_trip_id_979105_idx'),
        ),
        migrations.AddIndex(
            model_name='compliancereport',
            index=models.Index(fields=['is_compliant', '-created_at'], name='trip_api_co_is_comp_a0b1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='hosperiod',
            index=models.Index(fields=['trip', 'start_datetime'], name='trip_api_ho_trip_id_6406a9_idx'),
        ),
        migrations.AddIndex(
            model_name='hosperiod',
            index=models.Index(fields=['trip', 'duty_status'], name='trip_api_ho_trip_id_0ad790_idx'),
        ),
        migrations.AddIndex(
            model_name='hosperiod',
            index=models.Index(fields=['duty_status', 'start_datetime'], name='trip_api_ho_duty_st_7ddd33_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['trip', '-created_at'], name='trip_api_ro_trip_id_a9f984_idx'),
        ),
        migrations.AddIndex(
            model_name='stops',
            index=models.Index(fields=['trip', 'sequence_order'], name='trip_api_st_trip_id_23ae83_idx'),
        ),
        migrations.AddIndex(
            model_name='stops',
            index=models.Index(fields=['trip', 'stop_type'], name='trip_api_st_trip_id_9f2adc_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['driver', '-created_at'], name='trip_api_tr_driver__755f37_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['company', '-created_at'], name='trip_api_tr_company_fcec1d_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status', '-created_at'], name='trip_api_tr_status_4b7a5e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['assigned_vehicle', '-created_at'], name='trip_api_tr_assigne_f2e04a_idx'),
        ),
    ]
