# Generated by Django 5.2.1 on 2025-06-12 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_api', '0002_alter_compliancereport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='deadhead_distance_miles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from current location to pickup in miles', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='deadhead_driving_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Driving time for deadhead leg in hours', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_address',
            field=models.CharField(default=1, help_text='Final delivery location', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_latitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='delivery_longitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='estimated_pickup_time',
            field=models.DateTimeField(blank=True, help_text='Estimated arrival time at pickup location', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='loaded_distance_miles',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance from pickup to delivery in miles', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='loaded_driving_time',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Driving time for loaded leg in hours', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_address',
            field=models.CharField(default=1, help_text='Where to pick up cargo', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_latitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='pickup_longitude',
            field=models.DecimalField(decimal_places=7, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_address',
            field=models.CharField(help_text="Driver's current location", max_length=500),
        ),
    ]
