# Generated by Django 5.2.1 on 2025-06-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_api', '0003_trip_deadhead_distance_miles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When trip was completed', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='hos_updated',
            field=models.BooleanField(default=False, help_text='Whether driver cycle status has been updated for this trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='starting_cycle_hours',
            field=models.FloatField(blank=True, help_text="Driver's cycle hours when trip started", null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='starting_driving_hours',
            field=models.FloatField(blank=True, help_text="Driver's daily driving hours when trip started", null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='starting_duty_status',
            field=models.CharField(blank=True, choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], help_text="Driver's duty status when trip started", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='starting_on_duty_hours',
            field=models.FloatField(blank=True, help_text="Driver's daily on-duty hours when trip started", null=True),
        ),
    ]
