# Generated by Django 5.2.1 on 2025-06-24 19:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_api', '0004_trip_completed_at_trip_hos_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stops',
            name='amenity_name',
            field=models.CharField(blank=True, help_text='Name of the amenity/business', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stops',
            name='amenity_type',
            field=models.CharField(blank=True, help_text='Type of amenity (truck_stop, gas_station, etc.)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stops',
            name='available_amenities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='List of available amenities at this location', size=None),
        ),
        migrations.AddField(
            model_name='stops',
            name='break_reason',
            field=models.CharField(blank=True, help_text='Reason for this break (HOS compliance)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stops',
            name='is_24_hours',
            field=models.BooleanField(default=False, help_text='Whether location is open 24 hours'),
        ),
        migrations.AddField(
            model_name='stops',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stops',
            name='place_id',
            field=models.CharField(blank=True, help_text='External API place identifier', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stops',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Rating (0-5)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='stops',
            name='truck_friendly',
            field=models.BooleanField(default=False, help_text='Whether location is truck-friendly'),
        ),
        migrations.AddField(
            model_name='stops',
            name='website',
            field=models.URLField(blank=True, help_text='Website URL', null=True),
        ),
        migrations.AddIndex(
            model_name='stops',
            index=models.Index(fields=['amenity_type', 'truck_friendly'], name='trip_api_st_amenity_265717_idx'),
        ),
    ]
