# Generated by Django 5.2.1 on 2025-06-26 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_api', '0005_stops_amenity_name_stops_amenity_type_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stops',
            name='trip_api_st_amenity_265717_idx',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='amenity_name',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='amenity_type',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='available_amenities',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='break_reason',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='is_24_hours',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='place_id',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='truck_friendly',
        ),
        migrations.RemoveField(
            model_name='stops',
            name='website',
        ),
    ]
