# Generated by Django 5.2.1 on 2025-06-16 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_drivercyclestatus_dailydrivingrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivercyclestatus',
            name='today_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date these daily totals apply to'),
        ),
    ]
